### ISSUE TITLE
Jaguar should allow scaling up/down of individual resource index

### ISSUE THREAD

**Issue by ading1977** [TeraprocSoftware/jaguar#12]
Currently in Jaguar admin can only configure policy to scale up and down both resource indices (r.g., MEMORY and CPU) at the same time. This may not be desirable. A better option is to allow scaling up and down of only one resource index based on certain metrics.

**Comment by maweina** [comment]
Above commit include fix and following unit tests:
1. create policy with action only has one resource index: cpu or memory
2. scale up/down of both cpu and memory, covering three scaling types: delta, exact, percent
3. scale up/down of individual cpu
4. scale up/down of individual memory
5. scale up/down round-up to min/max because desired exceeds min/max resource
6. no action if desired scaling resource equals to allocated
